import os

class CoverLetterGenerator:
    def __init__(self, output_dir):
        self.output_dir = output_dir

    def generate(self, name, target_company, target_role, content):
        """
        In a real implementation, 'content' would be generated by the Critic agent
        to ensure it sounds human and references specific JD details.
        """
        filename = f"{name.replace(' ', '_')}_Cover_Letter_{target_company.replace(' ', '_')}.txt"
        file_path = os.path.join(self.output_dir, filename)

        # Simple template for now, though the LLM agent would provide the full body
        letter_template = f"""
Ali Husain Sorathiya
Dubai, UAE | +971-524678604
sorathiyaalihusain@gmail.com

Hiring Manager
{target_company}
Dubai, UAE

RE: {target_role} Application

Dear Hiring Manager,

{content}

Sincerely,

Ali Husain Sorathiya
"""
        with open(file_path, 'w') as f:
            f.write(letter_template.strip())

        print(f"Cover letter generated at {file_path}")
        return file_path

if __name__ == "__main__":
    gen = CoverLetterGenerator('ai-cover-letter')
    gen.generate("Ali Husain Sorathiya", "Example Corp", "Senior Product Manager",
                 "I was impressed by Example Corp's recent expansion into the KSA fintech market. With my background in API integrations and B2B SaaS at CAFU and Eyewa, I am confident I can help scale your integration roadmap.")
